baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'lbelchr'
theme = 'hugo-theme-console'

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast" 

  [[params.navlinks]]
  name = "skills/"
  url = "skills/"

  [[params.navlinks]]
  name = "culture/"
  url = "culture/"
  
  [[params.navlinks]]
  name = "leadership/"
  url = "leadership/"

